*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZDLPMVW_002.....................................*
FORM GET_DATA_ZDLPMVW_002.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZDLPMT_005 WHERE
(VIM_WHERETAB) .
    CLEAR ZDLPMVW_002 .
ZDLPMVW_002-MANDT =
ZDLPMT_005-MANDT .
ZDLPMVW_002-USUARIO =
ZDLPMT_005-USUARIO .
ZDLPMVW_002-EQUIPE =
ZDLPMT_005-EQUIPE .
<VIM_TOTAL_STRUC> = ZDLPMVW_002.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZDLPMVW_002 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZDLPMVW_002.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZDLPMVW_002-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZDLPMT_005 WHERE
  EQUIPE = ZDLPMVW_002-EQUIPE AND
  USUARIO = ZDLPMVW_002-USUARIO .
    IF SY-SUBRC = 0.
    DELETE ZDLPMT_005 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZDLPMT_005 WHERE
  EQUIPE = ZDLPMVW_002-EQUIPE AND
  USUARIO = ZDLPMVW_002-USUARIO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZDLPMT_005.
    ENDIF.
ZDLPMT_005-MANDT =
ZDLPMVW_002-MANDT .
ZDLPMT_005-USUARIO =
ZDLPMVW_002-USUARIO .
ZDLPMT_005-EQUIPE =
ZDLPMVW_002-EQUIPE .
    IF SY-SUBRC = 0.
    UPDATE ZDLPMT_005 ##WARN_OK.
    ELSE.
    INSERT ZDLPMT_005 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZDLPMVW_002-UPD_FLAG,
STATUS_ZDLPMVW_002-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZDLPMVW_002.
  SELECT SINGLE * FROM ZDLPMT_005 WHERE
EQUIPE = ZDLPMVW_002-EQUIPE AND
USUARIO = ZDLPMVW_002-USUARIO .
ZDLPMVW_002-MANDT =
ZDLPMT_005-MANDT .
ZDLPMVW_002-USUARIO =
ZDLPMT_005-USUARIO .
ZDLPMVW_002-EQUIPE =
ZDLPMT_005-EQUIPE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZDLPMVW_002 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZDLPMVW_002-EQUIPE TO
ZDLPMT_005-EQUIPE .
MOVE ZDLPMVW_002-USUARIO TO
ZDLPMT_005-USUARIO .
MOVE ZDLPMVW_002-MANDT TO
ZDLPMT_005-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZDLPMT_005'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZDLPMT_005 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZDLPMT_005'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
